### ISSUE TITLE
Precomputed language embeddings missing from 'D'

### ISSUE THREAD

**Issue by ezhang7423** [mees/calvin#22]
The `lang_paraphrase-MiniLM-L3-v2` embeddings is not present in [Split D->D](http://calvin.cs.uni-freiburg.de/dataset/task_D_D.zip) (166 GB)

**Comment by ezhang7423** [comment]
Ahh, I see you have them [here](https://github.com/lukashermann/hulc). This should probably be added to this repo as well?

**Comment by mees** [comment]
`lang_paraphrase-MiniLM-L3-v2` is not included in the original dataset, because the default language embeddings used were `paraphrase-MiniLM-L6-v2`. You can easily try out different language models with our following script https://github.com/mees/calvin#speech_balloon-relabeling-raw-language-annotations
