### ISSUE TITLE
"InvalidGitRepositoryError" while running jupyter notebook  

### ISSUE THREAD

**Issue by 2000222** [mees/calvin#5]
Hi, I'd like to run RL_with_CALVIN.ipynb file in my locally established environment, but I meet the following issue while running the line "env = hydra.utils.instantiate(cfg.env)":
‘InvalidGitRepositoryError: Error instantiating 'calvin_env.envs.play_table_env.PlayTableSimEnv' 
Exactly I don't know how to solve it, so please give more help.  

PS. it seems that there exists some script issues while opening RL_with_CALVIN.ipynb.

**Comment by ErickRosete** [comment]
Which cell do you run when this error appears? could you try it again and send me a screenshot of the the error please?

**Comment by ErickRosete** [comment]
We updated the google colab href to redirect to the appropriate branch, please let us know if the issue is still present after these changes.

**Comment by 2000222** [comment]
Actually I'm running RL_with_CALVIN.ipynb in my local machine since in colab I obtain issues on "numpy.core.multiarray failed to import" but I fixed it locally, and I've finished the previous cell step by step as follows: 
![issue1](https://user-images.githubusercontent.com/36289745/146502389-36b36949-bf06-4840-832d-69cf13d88718.png)

![issue2](https://user-images.githubusercontent.com/36289745/146502609-98913c62-22b3-4d13-8132-1171be56db89.png)

![issue3](https://user-images.githubusercontent.com/36289745/146503006-959dd81f-0166-47c0-b96b-3c0b4e5c1e37.png)

![issue4](https://user-images.githubusercontent.com/36289745/146503019-45674882-f5c0-486a-8a13-7888143a0a41.png)

![issue5](https://user-images.githubusercontent.com/36289745/146503037-4f438ca1-2330-45ab-bdd5-45647b6505f2.png)
 
I guess the problem is from calvin_env/utils/utils.py, but I'm not sure how to fix it. Thanks 💛

**Comment by ErickRosete** [comment]
Thanks for your reply, now that we know that you are running on a local machine, it is possible that the problem was the installation / cloning of the repo.
Did you clone the repository before starting to run the notebook?  is there a folder named ".git/" inside the calvin_env folder?


Note: you should be able to run it in colab, by following the instructions. The line:
`!pip3 install -U numpy`
Is used to avoid the "numpy.core.multiarray failed to import" error that is present in colab, you could try running it again and restarting the runtime after the installation.

**Comment by 2000222** [comment]
Thanks a lot, I've solved the problem in Colab usage ~~ 😃
