### ISSUE TITLE
Simulator Bug

### ISSUE THREAD

**Issue by H-ChanY** [mees/calvin#72]
Hello,

Thank you for your kindness. 

I'm encountering an error with the simulation you provided. 

When the robot pushes the block downwards, it vanishes under the desk. Here is the video showcasing the issue.

Thank you.

![trajectory-ezgif com-video-to-gif-converter](https://github.com/mees/calvin/assets/71515744/9804a3e5-ef3f-4fed-b092-a4916817f0a4)

**Comment by lukashermann** [comment]
Unfortunately, this is a known problem of pybullet collision handling which is caused by high forces and a high mass of the robot arm. If you wanted to create your own simulation, you could try to reduce the robot's mass and forces, but this would change the simulation dynamics, so we won't change this. From our experience, these situations didn't happen often enough to pose a serious problem.
