### ISSUE TITLE
Error in visualizing dataset

### ISSUE THREAD

**Issue by youngwoon** [mees/calvin#8]
Thank you for supporting this great benchmark!

I tried to run the [provided visualization code](https://github.com/mees/calvin/tree/main/dataset#visualize-language-annotations) but it failed due to several bugs. Here is a quick fix:
* In `calvin/calvin_models/cavin_agent/utils/visualize_annotations.py:84`  change `.avi` to `.mp4` and `*"XVID"` to `*"mp4v"`
* In `calvin/calvin_models/cavin_agent/utils/visualize_annotations.py:61`  change `dataset[start][1][0]` to `dataset[start]["rgb_obs"]["rgb_static"]`
* In `calvin/calvin_models/conf/lang_ann.yaml:14` comment out `override datamodule/observation_space: state_only`

**Comment by mees** [comment]
Thanks a lot for catching this @youngwoon !

- Changing avi to mp4 might be necessary due to missing codecs, but it is hard to tell what codecs or dependencies might be missing to avoid changing it. The current visualization code runs for me in at least three different ubuntu machines.
- This is a good catch, I forgot to refactor this bit of the code when I changed from using tuples to a dict.
- We mostly use the lang_ann conf for generating the language embeddings, this is why we override it with state_only observation as default. I have updated the instructions in the readme to note that one needs to override with datamodule/observation_space=lang_rgb_static to make the language annotation visualization work.
